name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          cache-dependency-path: package-lock.json
          node-version: 20.x
          cache: "npm"

      - name: Install dependencies
        working-directory: ./
        run: npm install

      - name: Prepare and deploy
        working-directory: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEMO_KEY: ${{secrets.DEMO_KEY }}
        run: |
          npm run deploy --base-href=/crypto-project/ --name="DmytroKryvak" --email="dimakryvak7@gmail.com"
